# Generated by Django 3.0.3 on 2020-03-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='finish',
            field=models.IntegerField(default=0),
        ),
    ]
