# Generated by Django 3.0.3 on 2020-03-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todos_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='finish',
            field=models.CharField(default='', max_length=100),
        ),
    ]
